### ISSUE TITLE
FREE Class: Setting Up Your Local Environment - 

### ISSUE THREAD

**Issue by N2IT** [learn-co-curriculum/phase-0-environment-setup-session#1]
### Canvas Link

https://learning.flatironschool.com/courses/7164/pages/free-class-setting-up-your-local-environment?module_item_id=597681

### Concern

Following the link to eventbrite lands on an event that is no longer available.

 

### Additional Context

The page within the SENG prep offers a CTA saying "Sign up here!" and leads you to think this is where you will learn how to build out your local environment. instead the eventbrite landing page is a dead end.  Its a confusing experience.

### Suggested Changes

Remove the "Sign Up Here" CTA / outbound link or reactivate the Eventbrite landing page

**Comment by Emiliotso** [comment]
I agree

**Comment by lizbur10** [comment]
Hi @N2IT! Thanks for bringing this to our attention. This class has been discontinued but the page was not removed from Canvas - it has now been removed. 

If you need assistance with your environment setup, see [this document](https://docs.google.com/document/d/1ot5ErJr0NivZvQ8yZ1VNOyi0ml6-w9qLujr-IbIrN0U/edit#heading=h.7c21co5sylgp) for ways to get help.
