### ISSUE TITLE
FREE Class: Setting Up Your Local Environment.  >>> Not available

### ISSUE THREAD

**Issue by Emiliotso** [learn-co-curriculum/phase-0-environment-setup-session#2]
### Canvas Link

https://learning.flatironschool.com/courses/7164/pages/free-class-setting-up-your-local-environment?module_item_id=597681

### Concern

the event is not available in eventbrite

**Comment by lizbur10** [comment]
Hi @Emiliotso ! Thanks for bringing this to our attention. This class has been discontinued but the page was not removed from Canvas - it has now been removed. 

If you need assistance with your environment setup, see [this document](https://docs.google.com/document/d/1ot5ErJr0NivZvQ8yZ1VNOyi0ml6-w9qLujr-IbIrN0U/edit#heading=h.7c21co5sylgp) for ways to get help.
